name: 'WordPress "Tested up to" Updater Action'
description:
  'Automatically updates the "Tested up to" strings in WordPress plugin files
  based on the latest versions of WordPress.'
author: 'Alec Rust'

branding:
  icon: 'corner-right-up'
  color: 'blue'

inputs:
  file-paths:
    description: 'File paths where the "Tested up to" string should be updated.'
    default: 'readme.txt'
  create-pr:
    description:
      'Flag setting if a pull request should be created for the changes.'
    default: 'true'
  git-author:
    description:
      'The name and email of the Git commit author in the format "name <email>".'
    default: 'github-actions <github-actions@noreply.github.com>'

outputs:
  updated:
    description: 'Indicates whether any files were updated (true or false).'

runs:
  using: 'node20'
  main: 'dist/index.js'
